# Generated by Django 2.1b1 on 2018-07-11 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Wifi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('bssid', models.CharField(max_length=17)),
                ('state', models.IntegerField(choices=[(1, 'Work'), (2, 'Home')], default=1)),
            ],
        ),
        migrations.AddField(
            model_name='tick',
            name='wifi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worktimer.Wifi'),
        ),
    ]
