# Generated by Django 2.1b1 on 2018-07-12 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktimer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wifi',
            old_name='name',
            new_name='essid',
        ),
        migrations.AlterField(
            model_name='tick',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 12, 17, 17, 26, 799697)),
        ),
        migrations.AlterField(
            model_name='tick',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 12, 17, 17, 26, 799673)),
        ),
    ]
