# Generated by Django 2.1.7 on 2019-05-22 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktimer', '0002_auto_20180712_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='tick',
            name='state',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Work'), (2, 'Home'), (3, 'Rest')], default=1),
        ),
        migrations.AlterField(
            model_name='tick',
            name='end',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='tick',
            name='start',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='wifi',
            name='state',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Work'), (2, 'Home')], default=1),
        ),
    ]
